#!/bin/sh

# Retrieve Sweet Home 3D directory
PROGRAM=`readlink "$0"`
PROGRAM_DIR=`dirname "$PROGRAM"`

# Run Sweet Home 3D
exec "$PROGRAM_DIR"/jre1.6.0_06/bin/java -classpath "$PROGRAM_DIR"/lib/SweetHome3D.jar:"$PROGRAM_DIR"/lib/Loader3DS1_2.jar:"$PROGRAM_DIR"/lib/iText-2.1.2u.jar:"$PROGRAM_DIR"/lib/j3dcore.jar:"$PROGRAM_DIR"/lib/j3dutils.jar:"$PROGRAM_DIR"/lib/vecmath.jar:"$PROGRAM_DIR"/jre1.6.0_06/lib/javaws.jar -Djava.library.path="$PROGRAM_DIR"/lib -Xmx384m com.eteks.sweethome3d.SweetHome3D -open $1
